Commerce/Buyer/urls.py
from django.contrib import admin
from django.urls import path,re_path
from Buyer.views import *
urlpatterns = [
    path('admin/', admin.site.urls),
    path('index/', index),
    path('login/', login),
    path('register/', register),
    path('logout/', logout),
    path('base/', base),
    path('goods_list/', goods_list),
    re_path(r'detail/(?P<id>\d{1,2})/', detail),
    path('user_info/', user_center_info),
    path('pay_order/', pay_order),
    path('pay_order_more/', pay_order_more),
    path('alipay/', AlipayView),
    path('pay_result/', pay_result),
    path('add_cart/', add_cart),
    path('cart/', cart),
    path('user_center_order/', user_center_order)
]

Commerce/Buyer/models.py
from django.db import models

from Seller.models import *

class PayOrder(models.Model):
    """
    订单表
    订单状态
    0 未支付
    1 已支付
    2 待发货
    3 待收货
    4/5 完成/拒收
    """
    order_number=models.CharField(max_length=32)    #订单编号
    order_data=models.DateTimeField(auto_now=True)   #订单时间
    # order_status=models.IntegerField()              #订单状态
    order_total=models.FloatField(blank=True,null=True)   #订单总价
    order_user=models.ForeignKey(to=LoginUser,on_delete=models.CASCADE)   #订单买家

class OrderInfo(models.Model):
    """
    订单详情表
    """
    order_id=models.ForeignKey(to=PayOrder,on_delete=models.CASCADE)  #对应订单表id
    goods_id=models.IntegerField()                   #订单id
    goods_picture = models.CharField(max_length=32)  #订单商品照片
    goods_name = models.CharField(max_length=32)     #订单商品名称
    goods_count = models.IntegerField()              #订单商品数量
    goods_price = models.FloatField()                #订单商品单钱
    goods_total_price = models.FloatField()    #订单商品总价
    order_status=models.IntegerField(default=0)
    store_id = models.ForeignKey(to=LoginUser,on_delete=models.CASCADE)  #商品对应商家


class Cart(models.Model):
    """
    购物车：
    商品id
    商品名称
    商品数量
    商品价格
    商品总价
    用户
    """
    goods_name=models.CharField(max_length=32)
    goods_number=models.IntegerField()
    goods_price=models.FloatField()
    goods_picture=models.CharField(max_length=32)
    goods_total=models.FloatField()
    goods_id=models.IntegerField()
    cart_user=models.IntegerField()
# Create your models here.

# Create your models here.

Commerce/Buyer/templates/buyer/base.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
	<title>{% block title %}天天生鲜-首页{% endblock %}</title>
	<link rel="stylesheet" type="text/css" href="/static/buyer/css/reset.css">
	<link rel="stylesheet" type="text/css" href="/static/buyer/css/main.css">
	<script type="text/javascript" src="/static/buyer/js/jquery-1.12.4.min.js"></script>
	<script type="text/javascript" src="/static/buyer/js/jquery-ui.min.js"></script>
	<script type="text/javascript" src="/static/buyer/js/slide.js"></script>
</head>
<body>
	<div class="header_con">
		<div class="header">
			<div class="welcome fl">欢迎来到天天生鲜!</div>
			<div class="fr">
				<div class="login_info fl">
					欢迎您：<em>张 山</em>
				</div>

                    {% if request.COOKIES.username %}
                        <div class="login_btn fl">
                            <em >欢迎{{ request.COOKIES.username }}</em>
                            <span>|</span>
                            <a href="/Buyer/logout/">退出</a>
                        </div>
                    {% else %}
                        <div class="login_btn fl">
                            <a  href="/Buyer/login/">登录</a>
                            <span>|</span>
                            <a href="/Buyer/register/">注册</a>
                        </div>
                    {% endif %}

				<div class="user_link fl">
					<span>|</span>
					<a href="/Buyer/user_info/">用户中心</a>
					<span>|</span>
					<a href="cart.html">我的购物车</a>
					<span>|</span>
					<a href="user_center_order.html">我的订单</a>
				</div>
			</div>
		</div>
	</div>

	<div class="search_bar clearfix">
		<a href="/Buyer/index/" class="logo fl"><img src="/static/buyer/images/logo.png"></a>
		<div class="search_con fl">
			<input id="search_key" type="text" class="input_text fl" placeholder="搜索商品">
			<input type="button" class="input_btn fr" name="" value="搜索" onclick="search()">
		</div>
		<div class="guest_cart fr">
			<a href="#" class="cart_name fl">我的购物车</a>
			<div class="goods_count fl" id="show_count">1</div>
		</div>
	</div>

	<div class="navbar_con">
		<div class="navbar clearfix">
			<div class="subnav_con fl">
				<h1>全部商品分类</h1>
				<span></span>
				<ul class="subnav">

					<li><a href="/Buyer/goods_list/?type=t&keywords=1" class="fruit">新鲜水果</a></li>
					<li><a href="/Buyer/goods_list/?type=t&keywords=2" class="seafood">海鲜水产</a></li>
					<li><a href="/Buyer/goods_list/?type=t&keywords=3" class="meet">猪牛羊肉</a></li>
					<li><a href="/Buyer/goods_list/?type=t&keywords=4" class="egg">禽类蛋品</a></li>
					<li><a href="/Buyer/goods_list/?type=t&keywords=5" class="vegetables">新鲜蔬菜</a></li>
					<li><a href="/Buyer/goods_list/?type=t&keywords=6" class="ice">速冻食品</a></li>

				</ul>
			</div>
			<ul class="navlist fl">
				<li><a href="/Buyer/index/">首页</a></li>
				<li class="interval">|</li>
				<li><a href="">手机生鲜</a></li>
				<li class="interval">|</li>
				<li><a href="">抽奖</a></li>
			</ul>
		</div>
	</div>

{% block content %}

{% endblock %}

	<div class="footer">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>
		</div>
		<p>CopyRight © 2016 北京天天生鲜信息技术有限公司 All Rights Reserved</p>
		<p>电话：010-****888    京ICP备*******8号</p>
	</div>
	<script type="text/javascript" src="/static/buyer/js/slideshow.js"></script>
	<script type="text/javascript">
		BCSlideshow('focuspic');
		var oFruit = document.getElementById('fruit_more');
		var oShownum = document.getElementById('show_count');

		var hasorder = localStorage.getItem('order_finish');

		if(hasorder)
		{
			oShownum.innerHTML = '2';
		}

		oFruit.onclick = function(){
			window.location.href = 'goods_list.html';
		};
		function search() {
		    var keywords=$("#search_key").val();
		    if(keywords){
		        var url="/Buyer/goods_list/?type=k&keywords="+keywords;
		        window.location.href=url
            }

        }


	</script>
        {% block script %}

        {% endblock %}
</body>
</html>

Commerce/Buyer/templates/buyer/cart.html
{% extends 'buyer/base.html' %}

{% block content %}

	<div class="total_count">全部商品<em>{{ count }}</em>件</div>
	<ul class="cart_list_th clearfix">
		<li class="col01">商品名称</li>
		<li class="col02">商品单位</li>
		<li class="col03">商品价格</li>
		<li class="col04">数量</li>
		<li class="col05">小计</li>
		<li class="col06">操作</li>
	</ul>
    <form action="/Buyer/pay_order_more/">
    {% for sta in cart %}
	<ul class="cart_list_td clearfix">
		<li class="col01"><input type="checkbox" class="goods_check" name="check_{{ sta.goods_id }}" ></li>
		<li class="col02"><img src="/static/{{ sta.goods_picture }}"></li>
		<li class="col03">{{ sta.goods_name }}<br><em>{{ sta.goods_price }}元/500g</em></li>
		<li class="col04">500g</li>
		<li class="col05">{{ sta.goods_price }}元</li>
		<li class="col06">
			<div class="num_add">
				<a href="javascript:;" class="add fl">+</a>
				<input type="text" class="num_show fl"  name="count_{{ sta.goods_id }}" value="{{ sta.goods_number }}">
				<a href="javascript:;" class="minus fl">-</a>	
			</div>
		</li>
		<li class="col07">{{ sta.goods_total }}元</li>
		<li class="col08"><a href="javascript:;">删除</a></li>
	</ul>

    {% endfor %}

	

	<ul class="settlements">
		<li class="col01"><input type="checkbox" name="" id="allBox"></li>
		<li class="col02">全选</li>
		<li class="col03">合计(不含运费)：<span>¥</span><em>{{ total }}</em><br>共计<b>{{ count }}</b>件商品</li>
		<li class="col04"><input type="submit" value="去结算"></li>
	</ul>
    </form>
{% endblock %}

{% block script %}
    <script>
        $('#allBox').click(
            function () {
                if(this.checked){
                    $('.goods_check').prop('checked',true)
                }else {
                    $(".goods_check").prop("checked", false)
                }
            }
        );
        $('.goods_check').each(
            function () {
                $(this).click(
                    function () {
                        if(!this.checked){
                            $('#allBox').prop('checked',false)
                        }
                    }
                )
            }
        )
    </script>
{% endblock %}

Commerce/Buyer/templates/buyer/detail.html
{% extends 'buyer/base.html' %}


{% block content %}

	<div class="goods_detail_con clearfix">
		<div class="goods_detail_pic fl"><img style="width: 100%;height: 100%" src="/static/{{ goods.goods_photo }}"></div>

		<div class="goods_detail_list fr">
			<h3>{{ goods.goods_name }}</h3>
			<p>{{ goods.goods_location }}</p>
			<div class="prize_bar">
				<span class="show_pirze">¥<em id="price">{{ goods.goods_price }}</em></span>
				<span class="show_unit">单  位：500g</span>
			</div>
			<div class="goods_num clearfix">
				<div class="num_name fl" >数 量：</div>
				<div class="num_add fl">
					<input id="number" type="text" class="num_show fl" value="1">
					<a id="add" href="javascript:;" class="add fr">+</a>
					<a id="reduce" href="javascript:;" class="minus fr">-</a>
				</div> 
			</div>
			<div class="total">总价：<em id="total">12.0</em><em>元</em></div>
			<div class="operate_btn">
				<a id="buy_now" href="javascript:;" class="buy_btn">立即购买</a>
				<a href="javascript:;" class="add_cart" id="add_cart">加入购物车</a>				
			</div>
		</div>
	</div>

	<div class="main_wrap clearfix">
		<div class="l_wrap fl clearfix">
			<div class="new_goods">
				<h3>新品推荐</h3>
				<ul>
					<li>
						<a href="#"><img src="images/goods/goods001.jpg"></a>
						<h4><a href="#">进口柠檬</a></h4>
						<div class="prize">￥3.90</div>
					</li>
					<li>
						<a href="#"><img src="images/goods/goods002.jpg"></a>
						<h4><a href="#">玫瑰香葡萄</a></h4>
						<div class="prize">￥16.80</div>
					</li>
				</ul>
			</div>
		</div>

		<div class="r_wrap fr clearfix">
			<ul class="detail_tab clearfix">
				<li class="active">商品介绍</li>
				<li>评论</li>
			</ul>

			<div class="tab_content">
				<dl>
					<dt>商品详情：</dt>
					<dd>草莓采摘园位于北京大兴区 庞各庄镇四各庄村 ，每年1月-6月面向北京以及周围城市提供新鲜草莓采摘和精品礼盒装草莓，草莓品种多样丰富，个大香甜。所有草莓均严格按照有机标准培育，不使用任何化肥和农药。草莓在采摘期间免洗可以直接食用。欢迎喜欢草莓的市民前来采摘，也欢迎各大单位选购精品有机草莓礼盒，有机草莓礼盒是亲朋馈赠、福利送礼的最佳选择。 </dd>
				</dl>
			</div>

		</div>
	</div>
{% endblock %}
{% block script %}
    <script>
    $("#add").click(
            function (){
                value=parseInt($('#number').val());

                price=parseFloat($('#price').text());
                value=value+1;
                $('#number').val(value);
                total=value*price;
                $('#total').text(total);
            }
        );
		$('#reduce').click(
		    function () {
                value=parseInt($('#number').val());
                price=parseFloat($('#price').text());
                if (value>1){
                    value=value-1;
                    $('#number').val(value);
                }
                else {
                    $('#number').val(1);
                }
                total=value*price;
                $('#total').text(total);
            }
        );
		$("#buy_now").click(
		    function () {
                url='/Buyer/pay_order/?goods_id={{ goods.id }}&count='+$("#number").val()
                window.location.href=url
            }
        )
    </script>
{% endblock %}

Commerce/Buyer/templates/buyer/goods_list.html
{% extends 'buyer/base.html' %}


{% block content %}
	<div class="breadcrumb">
		<a href="#">全部分类</a>
		<span>></span>
		<a href="#">新鲜水果</a>
	</div>
    {% if goods_list %}
	<div class="main_wrap clearfix">
		<div class="l_wrap fl clearfix">
			<div class="new_goods">
				<h3>新品推荐</h3>
				<ul>
                    {% for goods in recommend %}
					<li>
						<a href="#"><img src="/static/{{ goods.goods_photo }}"></a>
						<h4><a href="#">{{ goods.goods_name }}</a></h4>
						<div class="prize">￥{{ goods.goods_price }}</div>
					</li>
                    {% endfor %}

				</ul>
			</div>
		</div>

		<div class="r_wrap fr clearfix">
			<div class="sort_bar">
				<a href="#" class="active">默认</a>
				<a href="#">价格</a>
				<a href="#">人气</a>
			</div>

			<ul class="goods_type_list clearfix">

                {% for goods in goods_list %}
				<li>
					<a href="detail.html"><img src="/static/{{ goods.goods_photo }}"></a>
					<h4><a href="detail.html">{{ goods.goods_name }}</a></h4>
					<div class="operate">
						<span class="prize">￥{{ goods.goods_price }}</span>
						<span class="unit">16.80/500g</span>
						<a id="{{ goods.id }}" href="#" class="add_goods" title="加入购物车" onclick="add_cart(this)"></a>
					</div>
				</li>
                {% endfor %}

			</ul>

			<div class="pagenation">
				<a href="#"><上一页</a>
				<a href="#" class="active">1</a>
				<a href="#">2</a>
				<a href="#">3</a>
				<a href="#">4</a>
				<a href="#">5</a>
				<a href="#">下一页></a>
			</div>
		</div>
    {% else %}
        <p style="text-align: center">暂无查找，是否尝试查找<a>瓜</a></p>
    {% endif %}
	</div>
{% endblock %}

{% block script %}
    <script>
        function add_cart(obj) {
            var goods_id=obj.id;
            var csrf_token='{{ csrf_token }}';
            var sendData={
                'goods_id':goods_id,
                'csrfmiddlewaretoken':csrf_token
            };
            $.ajax(
                {
                    url:'/Buyer/add_cart/',
                    type:'POST',
                    data:sendData,
                    success:function (data) {
                        console.log(data)
                    },
                    error:function (error) {
                        console.log(error)
                    }
                }
            )
        }
    </script>
{% endblock %}

Commerce/Buyer/templates/buyer/index.html
{% extends 'buyer/base.html' %}

{% block content %}

    <div class="center_con clearfix">
            <ul class="subnav fl">
                {% for type in goods_type %}
                <li><a href="/Buyer/goods_list/?type=t&keywords={{ type.id }}" class="fruit">{{ type.type_label }}</a></li>
                {% endfor %}
<!--             <li><a href="#model01" class="fruit">新鲜水果</a></li>
                <li><a href="#model02" class="seafood">海鲜水产</a></li>
                <li><a href="#model03" class="meet">猪牛羊肉</a></li>
                <li><a href="#model04" class="egg">禽类蛋品</a></li>
                <li><a href="#model05" class="vegetables">新鲜蔬菜</a></li>
                <li><a href="#model06" class="ice">速冻食品</a></li>
-->
            </ul>
            <div class="slide fl">
                <ul class="slide_pics">
                    <li><img src="/static/buyer/images/slide.jpg" alt="幻灯片"></li>
                    <li><img src="/static/buyer/images/slide02.jpg" alt="幻灯片"></li>
                    <li><img src="/static/buyer/images/slide03.jpg" alt="幻灯片"></li>
                    <li><img src="/static/buyer/images/slide04.jpg" alt="幻灯片"></li>
                </ul>
                <div class="prev"></div>
                <div class="next"></div>
                <ul class="points"></ul>
            </div>
            <div class="adv fl">
                <a href="#"><img src="/static/buyer/images/adv01.jpg"></a>
                <a href="#"><img src="/static/buyer/images/adv02.jpg"></a>
            </div>
        </div>

    {% for get in result %}
        <div class="list_model">
            <div class="list_title clearfix">
                <h3 class="fl">{{ get.type.type_label}}</h3>
                <div class="subtitle fl">
                    <span>|</span>
                    <a href="#">鲜芒</a>
                    <a href="#">加州提子</a>
                    <a href="#">亚马逊牛油果</a>
                </div>
                <a href="/Buyer/goods_list/?type=t&keywords={{ get.type.id }}" class="goods_more fr" id="fruit_more">查看更多 ></a>
            </div>

            <div class="goods_con clearfix">
                <div class="goods_banner fl"><img src="/static/{{ get.type.type_photo }}"></div>
                <ul class="goods_list fl">
                    {% for goods in get.goods_list %}
                    <li>
                        <h4><a href="#">{{ goods.goods_name }}</a></h4>
                        <a href="/Buyer/detail/{{ goods.id }}/"><img src="/static/{{ goods.goods_photo }}"></a>
                        <div class="prize">{{ goods.goods_price }}</div>
                    </li>
                    {% endfor %}

                </ul>
            </div>
        </div>
    {% endfor %}

{% endblock %}

Commerce/Buyer/templates/buyer/login.html
<!DOCTYPE html>
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
	<title>Tan博客-登录</title>
	<link rel="stylesheet" type="text/css" href="/static/buyer/css/reset.css">
	<link rel="stylesheet" type="text/css" href="/static/buyer/css/main.css">
</head>
<body>
	<div class="login_top clearfix">
		<a href="index.html" class="login_logo"><img src="/static/buyer/images/logo02.png"></a>
	</div>

	<div class="login_form_bg">
		<div class="login_form_wrap clearfix">
			<div class="login_banner fl"></div>
			<div class="slogan fl">日夜兼程 · 急速送达</div>
			<div class="login_form fr">
				<div class="login_title clearfix">
					<h1>用户登录</h1>
					<a href="/Buyer/register/">立即注册</a>
				</div>
				<div class="form_input">
					<form method="post" >
                        {% csrf_token %}
						<input type="text" name="username" class="name_input" placeholder="请输入用户名">
						<div class="user_error">输入错误</div>
						<input type="password" name="password" class="pass_input" placeholder="请输入密码">
						<div class="pwd_error">输入错误</div>
						<div class="more_input clearfix">
							<input type="checkbox" name="">
							<label>记住用户名</label>
							<a href="#">忘记密码</a>
						</div>
						<input href="/Buyer/index/" type="submit" name="" value="登录" class="input_submit">
                        <p style="color: red">{{ error_message }}</p>
					</form>

				</div>
			</div>
		</div>
	</div>

	<div class="footer no-mp">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>		
		</div>
		<p>CopyRight © 2016 北京天天生鲜信息技术有限公司 All Rights Reserved</p>
		<p>电话：010-****888    京ICP备*******8号</p>
	</div>
	
</body>
</html>

Commerce/Buyer/templates/buyer/pay_order.html
{% extends 'buyer/base.html' %}

{% block content %}
	<div class="search_bar clearfix">
		<a href="index.html" class="logo fl"></a>
		<div class="sub_page_name fl">|&nbsp;&nbsp;&nbsp;&nbsp;提交订单</div>

	</div>
	
	<h3 class="common_title">确认收货地址</h3>

	<div class="common_list_con clearfix">
		<dl>
			<dt>寄送到：</dt>
			<dd><input type="radio" name="" checked="">北京市 海淀区 东北旺西路8号中关村软件园 （李思 收） 182****7528</dd>
		</dl>
		<a href="user_center_site.html" class="edit_site">编辑收货地址</a>

	</div>
	
	<h3 class="common_title">支付方式</h3>	
	<div class="common_list_con clearfix">
		<div class="pay_style_con clearfix">
			<input type="radio" name="pay_style" checked>
			<label class="cash">货到付款</label>
			<input type="radio" name="pay_style">
			<label class="weixin">微信支付</label>
			<input type="radio" name="pay_style" checked>
			<label class="zhifubao"></label>
			<input type="radio" name="pay_style">
			<label class="bank">银行卡支付</label>
		</div>
	</div>

	<h3 class="common_title">商品列表</h3>
	
	<div class="common_list_con clearfix">
		<ul class="goods_list_th clearfix">
			<li class="col01">商品名称</li>
			<li class="col02">商品单位</li>
			<li class="col03">商品价格</li>
			<li class="col04">数量</li>
			<li class="col05">小计</li>		
		</ul>
        {% for goods in order.orderinfo_set.all %}
		<ul class="goods_list_td clearfix">
			<li class="col01">1</li>			
			<li class="col02"><img src="/static/{{ goods.goods_picture}}"></li>
			<li class="col03">{{ goods.goods_name }}</li>
			<li class="col04">500g</li>
			<li class="col05">{{ goods.goods_price }}元</li>
			<li class="col06">{{ goods.goods_count }}</li>
			<li class="col07">{{ goods.goods_total_price }}元</li>
		</ul>
        {% endfor %}

	</div>

	<h3 class="common_title">总金额结算</h3>

	<div class="common_list_con clearfix">
		<div class="settle_con">
			<div class="total_goods_count">共<em>2</em>件商品，总金额<b>{{ order.order_total }}元</b></div>
			<div class="transit">运费：<b>0元</b></div>
			<div class="total_pay">实付款：<b>{{ order.order_total }}元</b></div>
		</div>
	</div>

	<div class="order_submit clearfix">
		<a href="/Buyer/alipay/?order_number={{ order.order_number }}&total={{ order.order_total }}" id="order_btn">提交订单</a>
	</div>	

{% endblock %}

Commerce/Buyer/templates/buyer/pay_result.html
{% extends 'buyer/base.html' %}

{% block content %}
    <div>
    <h1>付款完成</h1>
    <table>
        {% for k,v in request.GET.items %}
            <tr>
            <th>{{ k }}</th>
            <td>{{ v }}</td>
            </tr>
        {% endfor %}

    </table>
    </div>
{% endblock %}

Commerce/Buyer/templates/buyer/user_center_order.html
{% extends "buyer/base.html" %}

{% block title %}
    用户订单
{% endblock %}

{% block content %}
	<div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href="/Buyer/user_info/">· 个人信息</a></li>
				<li><a href="/Buyer/uco/" class="active">· 全部订单</a></li>
				<li><a href="user_center_site.html">· 收货地址</a></li>
			</ul>
		</div>
		<div class="right_content clearfix">
				<h3 class="common_title2">全部订单</h3>

                {% for order in order_list %}
				<ul class="order_list_th w978 clearfix">
					<li class="col01">{{ order.order_data }}</li>
					<li class="col02">订单号：{{ order.order_number }}</li>
                    {% ifequal order.order_status 0 %}
					    <li class="col02 stress">未支付</li>
                    {% endifequal %}
                    {% ifequal order.order_status 1 %}
					    <li class="col02 stress">已支付</li>
                    {% endifequal %}
                    {% ifequal order.order_status 2 %}
					    <li class="col02 stress">代发货</li>
                    {% endifequal %}
                    {% ifequal order.order_status 3 %}
					    <li class="col02 stress">待收货</li>
                    {% endifequal %}
                    {% ifequal order.order_status 4 %}
					    <li class="col02 stress">完成</li>
                    {% endifequal %}

				</ul>

				<table class="order_list_table w980">
					<tbody>
						<tr>
							<td width="55%">
                                {% for o in order.orderinfo_set.all %}
								<ul class="order_goods_list clearfix">
									<li class="col01"><img src="/static/{{ o.goods_picture }}"></li>
									<li class="col02">{{ o.goods_name }}<em>{{ o.goods_price }}元/500g</em></li>
									<li class="col03">{{ o.goods_count }}</li>
									<li class="col04">{{ o.goods_total_price }}元</li>
								</ul>
                                {% endfor %}
							</td>
							<td width="15%">{{ order.order_total }}元</td>

                            {% ifequal order.order_status 0 %}
                                <td width="15%">未支付</td>
                            {% endifequal %}
                            {% ifequal order.order_status 1 %}
                                <td width="15%">已支付</td>
                            {% endifequal %}
                            {% ifequal order.order_status 2 %}
                                <td width="15%">代发货</td>
                            {% endifequal %}
                            {% ifequal order.order_status 3 %}
                                <td width="15%">待收货</td>
                            {% endifequal %}
                            {% ifequal order.order_status 4 %}
                                <td width="15%">完成</td>
                            {% endifequal %}

                            {% ifequal order.order_status 0 %}
                                <td width="15%"><a href="/Buyer/alipay/?order_number={{ order.order_number }}&total={{ order.order_total }}" class="oper_btn">去付款</a></td>
                            {% else %}
                                <td width="15%"><a href="#" class="oper_btn">查看详情</a></td>
                            {% endifequal %}
						</tr>
					</tbody>
				</table>
                {% endfor %}


				<div class="pagenation">
					<a href="#"><上一页</a>
					<a href="#" class="active">1</a>
					<a href="#">2</a>
					<a href="#">3</a>
					<a href="#">4</a>
					<a href="#">5</a>
					<a href="#">下一页></a>
				</div>
		</div>
	</div>
{% endblock %}